/*
	"I'm just hoping we can get SF textures extracted soon, considering that's what we have leftover from shapeshifters"
		-Eon#9251 (User ID: 327591396343283713), 18/12/2021 at 16:22 GMT

	"i got textures from sg, stt, and ssc, ssf is pretty easy to add"
		-Neffy#5039 (User ID: 909500422006390874), 18/12/2021 at 16:23 GMT

	"if y'all want ssf texture extraction you're gonna have to cry cos this wayyy more complicated than i thought"
		-Neffy#5039 (User ID: 909500422006390874), 18/12/2021 at 18:33 GMT

	Why did you do this to me Eon?!
*/

//This file is autogenerated

//The strings (names of the enum items) are used to calculate hashes (their values), algorithm is fnv1a32, https://fnv1a32.cryptohash.net/

namespace LibSkydra
{

}